"""adding quantity to order item

Revision ID: 03aa5c216b59
Revises: 868a083ecfc4
Create Date: 2024-02-24 22:50:51.397446

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "03aa5c216b59"
down_revision: Union[str, None] = "868a083ecfc4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "order_items", sa.Column("quantity", sa.Integer(), nullable=True)
    )
    op.alter_column(
        "product", "quantity", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column(
        "product", "quantity", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_column("order_items", "quantity")

    # ### end Alembic commands ###
