"""Adding CPF field to user model

Revision ID: 48fdb7a41258
Revises: 9a009c50a0d9
Create Date: 2023-12-09 06:28:39.922869

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "48fdb7a41258"
down_revision: Union[str, None] = "9a009c50a0d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("cpf", sa.String(length=14), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "cpf")
    # ### end Alembic commands ###
