"""add status to order detail

Revision ID: 67eeee775909
Revises: 03aa5c216b59
Create Date: 2024-02-24 23:47:14.694331

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "67eeee775909"
down_revision: Union[str, None] = "03aa5c216b59"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment_details",
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("provider", sa.String(length=50), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "captured", "declined", "pending", name="paymentstatusenum"
            ),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["order_details.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "order_details", sa.Column("status", sa.String(), nullable=True)
    )
    op.drop_index("ix_users_id", table_name="users")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_users_id", "users", ["id"], unique=False)
    op.drop_column("order_details", "status")
    op.drop_table("payment_details")
    # ### end Alembic commands ###
