"""add qr_data to payment

Revision ID: 78f98f8cdb50
Revises: 7cc2fe02a82a
Create Date: 2024-03-02 22:36:45.945998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78f98f8cdb50'
down_revision: Union[str, None] = '7cc2fe02a82a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_details', sa.Column('qr_data', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_details', 'qr_data')
    # ### end Alembic commands ###
