"""add user_id to payment model

Revision ID: 7cc2fe02a82a
Revises: 67eeee775909
Create Date: 2024-03-02 18:19:08.472217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cc2fe02a82a'
down_revision: Union[str, None] = '67eeee775909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_details', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'payment_details', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment_details', type_='foreignkey')
    op.drop_column('payment_details', 'user_id')
    # ### end Alembic commands ###
