repos:
  - repo: local
    hooks:
      - id: black
        name: black
        language: system
        entry: bash -c '. venv/Scripts/activate && python -m black --line-length 79 .'
      - id: flake8
        name: flake8
        language: system
        entry: bash -c '. venv/Scripts/activate && python -m flake8 .'
