apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-postech-selfservice-fastfood-nginx-deployment
  namespace: postech
  labels:
    app: fiap-postech-selfservice-fastfood
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fiap-postech-selfservice-fastfood-nginx
  template:
    metadata:
      labels:
        app: fiap-postech-selfservice-fastfood-nginx
    spec:
      containers:
        - image: nginx:1.21
          name: nginx-container
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              port: 80
              path: /docs
            initialDelaySeconds: 15
          livenessProbe:
            httpGet:
              port: 80
              path: /docs
            initialDelaySeconds: 15
            periodSeconds: 15
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config