apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: postech
  labels:
    app: fiap-postech-selfservice-fastfood
spec:
  type: NodePort
  selector:
    app: fiap-postech-selfservice-fastfood-nginx-deployment
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30009