apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-postech-selfservice-fastfood
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fiap-postech-selfservice-fastfood
  template:
    metadata:
      labels:
        app: fiap-postech-selfservice-fastfood
    spec:
      containers:
      - name: fiap-postech-selfservice-fastfood
        image: alorencatto/fiap-postech-selfservice-fastfood:latest
#        command: ["bash","-c","while","!</dev/tcp/postgres/5432",";","do","sleep","1",";","done",";","uvicorn","src.infrastructure.http.app:app","--host","0.0.0.0","--port","8000","--reload"]
        command: ["uvicorn","src.infrastructure.http.app:app","--host","0.0.0.0","--port","8000","--reload"]
#        command: "bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; uvicorn src.infrastructure.http.app:app --host 0.0.0.0 --port 8000 --reload'"
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            port: 8000
            path: /docs
          initialDelaySeconds: 15
        livenessProbe:
          httpGet:
            port: 8000
            path: /docs
          initialDelaySeconds: 15
          periodSeconds: 15
        resources:
          requests:
            memory: "512Mi"
            cpu: "0.5"
          limits:
            memory: "1Gi"
            cpu: "1"
        env:
          - name: DATABASE_URL
            valueFrom:
              configMapKeyRef:
                name: config-fiap-postech-selfservice-fastfood
                key: DATABASE_URL