apiVersion: v1
kind: Secret
metadata:
  name: secret-fiap-postech-selfservice-fastfood
type: Opaque
data:
  DATABASE_URL: "cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzLXNlcnZpY2U6NTQzMi9wb3N0ZWNoX3NlbGZzZXJ2aWNlX2Zhc3Rmb29k"  # postgresql://postgres:postgres@postgres-service:5432/postech_selfservice_fastfood
