apiVersion: v1
kind: Service
metadata:
  name: svc-fiap-postech-selfservice-fastfood
spec:
  selector:
    app: fiap-postech-selfservice-fastfood
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
#  type: LoadBalancer